# column_width = 120
# line_endings = "Unix"
# indent_type = "Spaces"
# indent_width = 4
# quote_style = "AutoPreferDouble"
# call_parentheses = "Always"


column_width = 80
indent_type = "Spaces"
indent_width = 4
no_call_parentheses = true
