require("options")
require("keybindings")
require("plugins")

require("after/nv-tree")
require("after/nv-autopairs")
require("after/nv-bufferline")
require("after/nv-neoscroll")
require("after/nv-treesitter")
require("after/nv-lualine")
require("after/nv-formatter")
require("after/nv-lspconfig")
require("after/nv-completion")
require("after/nv-rusttool")
require("after/nv-indent")
require("after/nv-gitsigns")
require("after/nv-dap")
require("after/nv-luasnip")

vim.cmd([[colorscheme Nightfox]])
